#!/bin/bash

#missing s390x
#gcr.io/kubernetes-e2e-test-images/redis:1.0
#gcr.io/google-samples/gb-frontend:v6
#gcr.io/google-samples/gb-redisslave:v3
#gcr.io/kubernetes-e2e-test-images/dnsutils:1.1
#gcr.io/kubernetes-e2e-test-images/jessie-dnsutils:1.0

#buildah bud -t gcr.io/kubernetes-e2e-test-images/hostexec:1.1 .
#gcr.io/kubernetes-e2e-test-images/hostexec:1.1




export pullcmd="buildah pull"



echo ${pullcmd}
#1.15
${pullcmd} gcr.io/kubernetes-e2e-test-images/liveness:1.1
${pullcmd} docker.io/library/busybox:1.29
${pullcmd} quay.io/coreos/etcd:v3.3.10
${pullcmd} gcr.io/kubernetes-e2e-test-images/netexec:1.1
${pullcmd} gcr.io/kubernetes-e2e-test-images/sample-apiserver:1.10



#1.14
${pullcmd} docker.io/library/nginx:1.14-alpine
${pullcmd} docker.io/library/nginx:1.15-alpine
${pullcmd} docker.io/library/busybox:1.29
${pullcmd} gcr.io/kubernetes-e2e-test-images/netexec:1.1
${pullcmd} gcr.io/google-samples/gb-frontend:v6
${pullcmd} gcr.io/google-samples/gb-redisslave:v3
${pullcmd} gcr.io/kubernetes-e2e-test-images/dnsutils:1.1
${pullcmd} gcr.io/kubernetes-e2e-test-images/jessie-dnsutils:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/kitten:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/hostexec:1.1
${pullcmd} gcr.io/kubernetes-e2e-test-images/nettest:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/porter:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/entrypoint-tester:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/serve-hostname:1.1
${pullcmd} gcr.io/kubernetes-e2e-test-images/liveness:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/nautilus:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/mounttest:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/mounttest-user:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/redis:1.0
${pullcmd} gcr.io/kubernetes-e2e-test-images/test-webserver:1.0
${pullcmd} k8s.gcr.io/pause:3.1

